# Generated by Django 4.1.3 on 2022-11-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_crearpost_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearPost',
            new_name='Post',
        ),
    ]
