# Generated by Django 4.1.3 on 2022-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_crearpost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('terror', models.CharField(max_length=40)),
                ('fantasia', models.CharField(max_length=40)),
                ('aventuras', models.CharField(max_length=40)),
                ('ciencia_ficción', models.CharField(max_length=40)),
                ('comedia', models.CharField(max_length=40)),
                ('drama', models.CharField(max_length=40)),
                ('musical', models.CharField(max_length=40)),
                ('suspenso', models.CharField(max_length=40)),
            ],
        ),
    ]
