# Generated by Django 4.1.3 on 2022-11-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='aventuras',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='ciencia_ficción',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='comedia',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fantasia',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='musical',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='suspenso',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='terror',
        ),
    ]
