# Generated by Django 4.1.3 on 2022-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_autor_categoria_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=40)),
                ('reseña', models.CharField(max_length=240)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
