# Generated by Django 4.1.3 on 2022-11-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_reseña_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='nombre_pelicula',
            new_name='nombre',
        ),
    ]
