# Generated by Django 4.1.3 on 2022-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='genero',
            field=models.CharField(default='some_value', max_length=30),
        ),
        migrations.AddField(
            model_name='reseña',
            name='titulo',
            field=models.CharField(default='some_value', max_length=50),
        ),
    ]
