# Generated by Django 4.1.3 on 2022-12-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_reseña_genero_reseña_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
