# Generated by Django 4.1.3 on 2022-12-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
