# Generated by Django 4.1.3 on 2022-12-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_delete_autor_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='reseña',
            field=models.CharField(max_length=400),
        ),
    ]
